name: PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write
  pull-requests: write

jobs:
  test-robot-unlabel:
    if: github.event.action == 'synchronize'
    name: Job
    uses: ./.github/workflows/test-robot-unlabel.yml
    with:
      label-test-robot-done: test-robot-done
      label-test-robot-needed: test-robot-needed
    secrets:
      token: ${{ secrets.BOT_REPO_TOKEN }}

  build:
    needs: test-robot-unlabel
    if: ${{ !failure() && !cancelled() && needs.test-robot-unlabel.result != 'failure' }}
    name: Job
    uses: ./.github/workflows/build.yml

  test-robot-check:
    needs: build
    name: Job
    uses: ./.github/workflows/test-robot-check.yml
    with:
      label-test-robot-done: test-robot-done
      label-test-robot-needed: test-robot-needed

  all-green:
    needs: test-robot-check
    name: Job
    uses: ./.github/workflows/all-green.yml
