name: Release

on:
  push:
    branches:
      - main
      - master
    tags:
      - 'v*'

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

permissions:
  contents: write
  packages: write

jobs:
  build:
    name: Job
    uses: ./.github/workflows/build.yaml

  promote:
    name: Job
    needs: build
    uses: getdevopspro/github-actions/.github/workflows/promote.yml@v6.0.4
    secrets:
      # To bypass ruleset enforcing checks
      checkout-token: ${{ secrets.BOT_RELEASE_CHECKOUT_TOKEN }}
    with:
      version-package: package.json
      git-add-files: package.json
      git-user-name: getdevopspro-cibot
      git-user-email: 203600057+getdevopspro-cibot@users.noreply.github.com
      image-digests: ${{ needs.build.outputs.image-digests }}
