name: Robot Test Unlabel

on:
  workflow_call:
    inputs:
      label-test-robot-done:
        description: 'Label name indicating the PR has been test-robot-done'
        type: string
        required: false
        default: 'test-robot-done'
      label-test-robot-needed:
        description: 'Label name indicating the PR needs robot testing'
        type: string
        required: false
        default: 'test-robot-needed'
    secrets:
      token:
        description: 'PAT used to post comments'
        required: false

permissions:
  contents: read
  pull-requests: write

jobs:
  test-robot-unlabel:
    if: contains(github.event.pull_request.labels.*.name, inputs.label-test-robot-done)
    name: Robot Test Unlabel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Robot Test Unlabel
        uses: ./.github/actions/test/unlabel
        with:
          label-done: ${{ inputs.label-test-robot-done }}
          label-needed: ${{ inputs.label-test-robot-needed }}
          test-name: Robot
          token: ${{ secrets.token }}
