name: Robot Test Label

on:
  workflow_call:
    inputs:
      label-test-robot-done:
        description: 'Label name indicating the PR has been test-robot-done'
        type: string
        required: false
        default: 'test-robot-done'
      label-test-robot-needed:
        description: 'Label name indicating the PR needs robot testing'
        type: string
        required: false
        default: 'test-robot-needed'
    secrets:
      token:
        description: 'GitHub token or PAT'
        required: false

permissions:
  contents: read
  pull-requests: write
  actions: write

jobs:
  test-robot-label:
    if: github.event.action == 'labeled' &&
      github.event.label.name == inputs['label-test-robot-done']
    name: Robot Test Label
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Robot Test Label
        uses: getdevopspro/github-actions/test/label@v6.2.4
        with:
          label-done: ${{ inputs.label-test-robot-done }}
          label-needed: ${{ inputs.label-test-robot-needed }}
          test-name: Robot
          token: ${{ secrets.token }}

      - name: Rerun pull-request workflow
        uses: getdevopspro/github-actions/pr/checks-rerun@v6.2.4
        with:
          workflow-id: pull-request.yml
          token: ${{ secrets.token }}
