name: Robot Test Check

on:
  workflow_call:
    inputs:
      label-test-robot-done:
        description: 'Label name indicating the PR has been test-robot-done'
        type: string
        required: false
        default: 'test-robot-done'
      label-test-robot-needed:
        description: 'Label name indicating the PR needs robot testing'
        type: string
        required: false
        default: 'test-robot-needed'
    secrets:
      token:
        description: 'GitHub token or PAT'
        required: false

permissions:
  contents: read
  pull-requests: write

jobs:
  test-robot-check-labels:
    name: Robot Test Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Robot Test Check
        uses: getdevopspro/github-actions/test/label/check@v6.3.2
        with:
          label-done: ${{ inputs.label-test-robot-done }}
          label-needed: ${{ inputs.label-test-robot-needed }}
          test-name: Robot
          token: ${{ secrets.token }}
